name: Build and Package Angular app
on:
  push:
    branches:
      - master
jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
      - name: ignore cli diff
        run : ng config -g cli.warnings.versionMismatch false

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: ng build --prod

      - name: Build Docker image
        run: |
          docker build -t client-app .
          docker tag client-app:latest liyanamyc/client-app:latest
          docker push liyanamyc/client-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
