name: Build and Publish Angular App to Docker Hub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: liyanamyc
  DOCKER_HUB_PASSWORD: Liyana21@@
  DOCKER_ACCESS_TOKEN: dckr_pat_q2rLEaHmEudyjUxCK8ZQPJLNPKY

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: ng build --configuration production

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/my-angular-app:latest
        dockerfile: Dockerfile

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Push Docker Image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/my-angular-app:latest
        dockerfile: dockerfile
