name: Build and Publish Angular App to Docker Hub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build Angular App
      run: ng build --configuration production

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/my-angular-app:latest
        dockerfile: Dockerfile

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/my-angular-app:latest
        dockerfile: Dockerfile
